package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.Approval
import jetbrains.buildServer.configs.kotlin.buildFeatures.approval
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        val feature1 = find<Approval> {
            approval {
                approvalRules = "user:dts"
                manualRunsApproved = false
            }
        }
        feature1.apply {
            approvalRules = """
                user:dts
                user:mini-dts
            """.trimIndent()
        }
    }
}
